kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/route-disabled: 'false'
    deployment.kubernetes.io/revision: '2'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"mqtt-publisher:latest","namespace":"team21-fiware"},"fieldPath":"spec.template.spec.containers[?(@.name==\"mqtt-publisher\")].image","pause":"false"}]
    openshift.io/generated-by: OpenShiftWebConsole
  resourceVersion: '1031442306'
  name: mqtt-publisher
  uid: f688d3b1-464c-4283-b800-db75d4daa3d9
  creationTimestamp: '2026-01-13T08:08:02Z'
  generation: 6
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: apps/v1
      time: '2026-01-13T08:42:56Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:alpha.image.policy.openshift.io/resolve-names': {}
            'f:app.openshift.io/route-disabled': {}
            'f:image.openshift.io/triggers': {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            'f:app.openshift.io/runtime': {}
            'f:app': {}
            'f:app.kubernetes.io/name': {}
            .: {}
            'f:app.kubernetes.io/part-of': {}
            'f:app.openshift.io/runtime-version': {}
            'f:app.openshift.io/runtime-namespace': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/component': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:annotations':
                .: {}
                'f:openshift.io/generated-by': {}
              'f:labels':
                .: {}
                'f:app': {}
                'f:deployment': {}
            'f:spec':
              'f:containers':
                'k:{"name":"mqtt-publisher"}':
                  'f:image': {}
                  'f:terminationMessagePolicy': {}
                  .: {}
                  'f:resources': {}
                  'f:env':
                    .: {}
                    'k:{"name":"MQTT_BROKER"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"MQTT_INTERVAL"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                  'f:terminationMessagePath': {}
                  'f:imagePullPolicy': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8080,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:name': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2026-01-21T13:21:35Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
      subresource: status
  namespace: team21-fiware
  labels:
    app: mqtt-publisher
    app.kubernetes.io/component: mqtt-publisher
    app.kubernetes.io/instance: mqtt-publisher
    app.kubernetes.io/name: mqtt-publisher
    app.kubernetes.io/part-of: 3D-Modell
    app.openshift.io/runtime: mqtt-publisher
    app.openshift.io/runtime-namespace: team21-fiware
    app.openshift.io/runtime-version: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-publisher
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mqtt-publisher
        deployment: mqtt-publisher
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      containers:
        - name: mqtt-publisher
          image: >-
            image-registry.openshift-image-registry.svc:5000/team21-fiware/mqtt-publisher@sha256:260e60b8e88fbdfa22421d49bab6141be610ce82d6e5676db76e5fff925d8c3c
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: MQTT_BROKER
              value: mosquitto
            - name: MQTT_INTERVAL
              value: '15'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 6
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2026-01-13T08:42:59Z'
      lastTransitionTime: '2026-01-13T08:08:02Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "mqtt-publisher-c8bd75b64" has successfully progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2026-01-21T13:21:35Z'
      lastTransitionTime: '2026-01-21T13:21:35Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
